# Generated by Django 4.2.11 on 2024-04-19 16:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loco',
            fields=[
                ('Serial', models.AutoField(primary_key=True, serialize=False)),
                ('RecordCreationDate', models.DateTimeField(default=django.utils.timezone.now)),
                ('LocoNumber', models.IntegerField(blank=True, null=True)),
                ('LocoType', models.CharField(blank=True, choices=[('SelectLoco', 'Please Select Loco Type'), ('WDG4', 'WDG4'), ('WDG4D', 'WDG4D'), ('WDP4', 'WDP4'), ('WDP4D', 'WDP4D'), ('WDP4B', 'WDP4B'), ('WDM3', 'WDM3'), ('WDM3D', 'WDM3D'), ('WDM3A', 'WDM3A'), ('WDG3A', 'WDG3A'), ('WDS6', 'WDS6'), ('WAP1', 'WAP1'), ('WAG7', 'WAG7'), ('WAG5', 'WAG5'), ('WAG11', 'WAG11'), ('WDS6AD', 'WDS6AD')], default='SelectLoco', max_length=11, null=True)),
                ('LocoCommDate', models.DateField(default='1001-01-01', null=True)),
                ('LocoFailed', models.BooleanField(blank=True, default=False)),
                ('LocoFile', models.FileField(blank=True, null=True, upload_to='Loco/%Y/%m/%d/')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='locoauth', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
